// examples/notes-reactive-views/Svelte/src/App.svelte
<script lang="ts">
  import { connectShell } from "../../Frontend/src/generated/shell.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";
  import Shell from "./Shell.svelte";

  const shell = useView(() => ({ connect: connectShell }));
</script>

{#if shell.client}
  <Shell shell={shell.client} />
{:else}
  <p id="status" role="status">{shell.error === undefined ? "Connecting…" : String(shell.error)}</p>
{/if}

// examples/notes-view-first/Angular/src/app/app.ts
import { Component, computed } from "@angular/core";
import { connectShell } from "../../../Frontend/src/generated/shell.js";
import { injectView } from "../../../../../packages/web/angular/src/inject-view";
import { ShellComponent } from "./shell";

@Component({
  selector: "app-root",
  imports: [ShellComponent],
  template: `
    @if (root.client(); as connected) {
      <notes-shell [shell]="connected" />
    } @else {
      <p id="status" role="status">{{ error() ?? "Connecting…" }}</p>
      @if (error()) { <button data-retry-root (click)="root.retry()">Retry</button> }
    }
  `,
})
export class App {
  readonly root = injectView({ connect: connectShell });
  readonly error = computed(() => this.root.error() === undefined ? undefined : String(this.root.error()));
}
