// examples/notes-view-first/Svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { connectShell, type ShellView } from "../../Frontend/src/generated/shell.js";
  import Shell from "./Shell.svelte";

  let shell = $state.raw<ShellView | undefined>();
  let error = $state<string | undefined>();

  onMount(() => {
    let active = true;
    let connected: ShellView | undefined;
    void connectShell().then(view => {
      if (!active) { view.dispose(); return; }
      connected = view;
      shell = view;
    }).catch(cause => { if (active) error = String(cause); });
    return () => {
      active = false;
      connected?.dispose();
    };
  });
</script>

{#if shell}
  <Shell {shell} />
{:else}
  <p id="status" role="status">{error ?? "Connecting…"}</p>
{/if}

// examples/notes-reactive-views/Angular/src/app/app.ts
import { Component, DestroyRef, inject, signal } from "@angular/core";
import { connectShell, type ShellView } from "../../../Frontend/src/generated/shell.js";
import { ShellComponent } from "./shell";

@Component({
  selector: "app-root",
  imports: [ShellComponent],
  template: `
    @if (shell(); as connected) { <notes-shell [shell]="connected" /> }
    @else { <p id="status" role="status">{{ error() ?? "Connecting…" }}</p> }
  `,
})
export class App {
  private readonly destroyRef = inject(DestroyRef);
  private connected: ShellView | undefined;
  readonly shell = signal<ShellView | undefined>(undefined);
  readonly error = signal<string | undefined>(undefined);

  constructor() {
    this.destroyRef.onDestroy(() => this.connected?.dispose());
    void connectShell().then(view => {
      if (this.destroyRef.destroyed) { view.dispose(); return; }
      this.connected = view;
      this.shell.set(view);
    }).catch(cause => { if (!this.destroyRef.destroyed) this.error.set(String(cause)); });
  }
}
