// examples/notes-reactive-views/Svelte/src/Editor.svelte
<script lang="ts">
  import type { EditorPageReference, EditorView } from "../../Frontend/src/generated/editor.js";
  import { EditorWrites } from "../../Frontend/src/editor-writes.js";
  import { pageState } from "./bridge-state.js";

  let { page, handleInteractions = true }: { page: EditorPageReference; handleInteractions?: boolean } = $props();
  const editor = pageState(() => page);
  let error = $state<string | undefined>();
  const writes = new EditorWrites(cause => { error = cause === undefined ? undefined : String(cause); });
  const connectedEditor = $derived(editor.view);

  $effect(() => {
    if (!connectedEditor || !handleInteractions) return;
    return connectedEditor.interactions.confirmDiscard.handle(async (request, { signal }) => {
      if (signal.aborted) throw signal.reason;
      return window.confirm(`Discard the ${request.bodyLength} unsaved characters in “${request.title}”?`);
    });
  });

  async function run(command: (view: EditorView) => Promise<unknown>) {
    const view = editor.view;
    if (!view) return;
    try { await command(view); error = undefined; }
    catch (cause) { error = String(cause); }
  }
  function write(command: (view: EditorView) => Promise<unknown>) {
    const view = editor.view;
    if (view) writes.enqueue(() => command(view));
  }
</script>

{#if editor.state}
  <h2>Full editor</h2>
  <label>Title<input data-title value={editor.state.title} onchange={event => { const value = event.currentTarget.value; write(view => view.setTitle(value)); }}></label>
  <label>Body<textarea data-body value={editor.state.body} onchange={event => { const value = event.currentTarget.value; write(view => view.setBody(value)); }}></textarea></label>
  <button data-save disabled={!editor.state.canSave} onclick={() => run(view => writes.run(() => view.save()))}>Save</button>
  <button data-discard disabled={!editor.state.canDiscard} onclick={() => run(view => writes.run(() => view.discard()))}>Discard changes</button>
  <p data-message role="status">{editor.state.savedMessage}</p>
  <p data-activation class="muted">Activated {editor.state.activationCount} × · deactivated {editor.state.deactivationCount} ×</p>
{:else}
  <p>Connecting…</p>
{/if}
{#if error ?? editor.error}<p role="alert">{String(error ?? editor.error)}</p>{/if}

// examples/notes-reactive-views/Angular/src/app/editor.ts
import { Component, effect, input, signal } from "@angular/core";
import type { EditorPageReference, EditorView } from "../../../Frontend/src/generated/editor.js";
import { EditorWrites } from "../../../Frontend/src/editor-writes.js";
import { pageSignal } from "./bridge-signal";

@Component({
  selector: "notes-editor",
  template: `
    @if (editor.state(); as state) {
      <h2>Full editor</h2>
      <label>Title<input data-title [value]="state.title" (change)="setTitle($event)" /></label>
      <label>Body<textarea data-body [value]="state.body" (change)="setBody($event)"></textarea></label>
      <button data-save [disabled]="!state.canSave" (click)="save()">Save</button>
      <button data-discard [disabled]="!state.canDiscard" (click)="discard()">Discard changes</button>
      <p data-message role="status">{{ state.savedMessage }}</p>
      <p data-activation class="muted">Activated {{ state.activationCount }} × · deactivated {{ state.deactivationCount }} ×</p>
    } @else { <p>Connecting…</p> }
    @if (error() ?? editor.error(); as issue) { <p role="alert">{{ issue }}</p> }
  `,
})
export class EditorComponent {
  readonly page = input.required<EditorPageReference>();
  readonly handleInteractions = input(true);
  readonly editor = pageSignal(this.page);
  readonly error = signal<string | undefined>(undefined);
  private readonly writes = new EditorWrites(cause => this.error.set(cause === undefined ? undefined : String(cause)));

  constructor() {
    effect(onCleanup => {
      const view = this.editor.view();
      if (!view || !this.handleInteractions()) return;
      onCleanup(view.interactions.confirmDiscard.handle(async (request, { signal }) => {
        if (signal.aborted) throw signal.reason;
        return window.confirm(`Discard the ${request.bodyLength} unsaved characters in “${request.title}”?`);
      }));
    });
  }

  setTitle(event: Event): void { const value = (event.target as HTMLInputElement).value; this.write(view => view.setTitle(value)); }
  setBody(event: Event): void { const value = (event.target as HTMLTextAreaElement).value; this.write(view => view.setBody(value)); }
  save(): void { this.run(view => this.writes.run(() => view.save())); }
  discard(): void { this.run(view => this.writes.run(() => view.discard())); }
  private write(action: (view: EditorView) => Promise<unknown>): void {
    const view = this.editor.view();
    if (view) this.writes.enqueue(() => action(view));
  }
  private run(action: (view: EditorView) => Promise<unknown>): void {
    const view = this.editor.view();
    if (!view) return;
    void action(view).then(() => this.error.set(undefined)).catch(cause => this.error.set(String(cause)));
  }
}

@Component({
  selector: "notes-mirror-editor",
  imports: [EditorComponent],
  template: `<notes-editor [page]="page()" [handleInteractions]="false" />`,
})
export class MirrorEditorComponent {
  readonly page = input.required<EditorPageReference>();
}
