// examples/notes-reactive-views/Svelte/src/Preview.svelte
<script lang="ts">
  import type { PreviewPageReference } from "../../Frontend/src/generated/preview.js";
  import { pageState } from "./bridge-state.js";
  let { page }: { page: PreviewPageReference } = $props();
  const preview = pageState(() => page);
</script>

{#if preview.state}
  <h2 data-heading>{preview.state.heading}</h2><p data-body>{preview.state.body}</p>
{:else}
  <p>Connecting…</p>
{/if}
{#if preview.error}<p role="alert">{String(preview.error)}</p>{/if}

// examples/notes-reactive-views/Angular/src/app/preview.ts
import { Component, input } from "@angular/core";
import type { PreviewPageReference } from "../../../Frontend/src/generated/preview.js";
import { pageSignal } from "./bridge-signal";

@Component({
  selector: "notes-preview",
  template: `
    @if (preview.state(); as state) { <h2 data-heading>{{ state.heading }}</h2><p data-body>{{ state.body }}</p> }
    @else { <p>Connecting…</p> }
    @if (preview.error(); as issue) { <p role="alert">{{ issue }}</p> }
  `,
})
export class PreviewComponent {
  readonly page = input.required<PreviewPageReference>();
  readonly preview = pageSignal(this.page);
}
