// tools/Runic.Application.Templates/content/runic-app/frontends/react/src/pages/CounterPage.tsx
import { useState } from "react";
import { useView } from "@runic-artifex/react";
import type { CounterPageReference } from "../generated/counter.js";

export function CounterPage({ page }: { page: CounterPageReference }) {
  const { state, client, error: connection } = useView(page);
  const [error, setError] = useState<string>();
  const shown = error ?? (connection ? String(connection) : undefined);

  return <section>
    <h2>Counter View</h2>
    <p className="count">{state?.count ?? "…"}</p>
    <button disabled={!client} onClick={() => client && void client.increment().then(() => setError(undefined), cause => setError(String(cause)))}>Increment</button>
    {shown && <p role="alert">{shown}</p>}
  </section>;
}

// tools/Runic.Application.Templates/content/vue/Frontend/src/pages/CounterPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { useView } from "@runic-artifex/vue";
import type { CounterPageReference } from "../generated/counter.js";

const props = defineProps<{ page: CounterPageReference }>();
const { state, client, error: connection } = useView(() => props.page);
const error = ref<string>();

async function increment() {
  try { await client.value?.increment(); error.value = undefined; }
  catch (cause) { error.value = String(cause); }
}
</script>

<template>
  <section>
    <h2>Counter View</h2>
    <p class="count">{{ state?.count ?? "…" }}</p>
    <button :disabled="!client" @click="increment">Increment</button>
    <p v-if="error ?? connection" role="alert">{{ error ?? String(connection) }}</p>
  </section>
</template>
