// tools/Runic.Application.Templates/content/svelte/Frontend/src/pages/CounterPage.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { useView } from "@runic-artifex/svelte/views";
  import type { CounterPageReference } from "../generated/counter.js";

  let { page }: { page: CounterPageReference } = $props();
  const counter = useView(() => page);
  let error = $state<string | undefined>(undefined);

  async function increment() {
    try { await counter.client?.increment(); error = undefined; }
    catch (cause) { error = String(cause); }
  }
</script>

<section>
  <h2>Counter View</h2>
  <p class="count">{counter.state?.count ?? "…"}</p>
  <button disabled={!counter.client} onclick={increment}>Increment</button>
  {#if error ?? counter.error}<p role="alert">{error ?? String(counter.error)}</p>{/if}
</section>

// tools/Runic.Application.Templates/content/vue/Frontend/src/pages/CounterPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { useView } from "@runic-artifex/vue";
import type { CounterPageReference } from "../generated/counter.js";

const props = defineProps<{ page: CounterPageReference }>();
const { state, client, error: connection } = useView(() => props.page);
const error = ref<string>();

async function increment() {
  try { await client.value?.increment(); error.value = undefined; }
  catch (cause) { error.value = String(cause); }
}
</script>

<template>
  <section>
    <h2>Counter View</h2>
    <p class="count">{{ state?.count ?? "…" }}</p>
    <button :disabled="!client" @click="increment">Increment</button>
    <p v-if="error ?? connection" role="alert">{{ error ?? String(connection) }}</p>
  </section>
</template>
