// tools/Runic.Application.Templates/content/angular/Frontend/src/app/app.ts
import { Component, OnDestroy, OnInit, signal } from "@angular/core";
import { RunicViewOutlet, type ViewRegistry } from "@runic-artifex/views-angular";
import { connectWorkspace, type WorkspaceState, type WorkspaceView } from "../generated/workspace.js";
import { CounterComponent } from "./counter";
import { WelcomeComponent } from "./welcome";

const pages = { counter: CounterComponent, welcome: WelcomeComponent } satisfies ViewRegistry<WorkspaceState["main"]>;

@Component({
  selector: "runic-app",
  imports: [RunicViewOutlet],
  templateUrl: "./app.html"
})
export class AppComponent implements OnInit, OnDestroy {
  readonly state = signal<WorkspaceState | undefined>(undefined);
  readonly workspace = signal<WorkspaceView | undefined>(undefined);
  readonly error = signal<string | undefined>(undefined);
  readonly pages = pages;
  private unsubscribe = () => {};
  private active = true;

  ngOnInit(): void {
    void connectWorkspace().then(client => {
      if (!this.active) { client.dispose(); return; }
      this.workspace.set(client);
      this.unsubscribe = client.subscribe(next => this.state.set(next));
    }).catch(cause => this.error.set(String(cause)));
  }

  ngOnDestroy(): void {
    this.active = false;
    this.unsubscribe();
    this.workspace()?.dispose();
  }

  showWelcome(): void {
    const client = this.workspace();
    if (client) void client.showWelcome().then(() => this.error.set(undefined)).catch(cause => this.error.set(String(cause)));
  }

  showCounter(): void {
    const client = this.workspace();
    if (client) void client.showCounter().then(() => this.error.set(undefined)).catch(cause => this.error.set(String(cause)));
  }
}

// tools/Runic.Application.Templates/content/svelte/Frontend/src/App.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { onMount } from "svelte";
  import { ViewOutlet, type ViewRegistry } from "@runic-artifex/svelte/views";
  import { connectWorkspace, type WorkspaceState, type WorkspaceView } from "./generated/workspace.js";
  import CounterPage from "./pages/CounterPage.svelte";
  import WelcomePage from "./pages/WelcomePage.svelte";

  const pages = { counter: CounterPage, welcome: WelcomePage } satisfies ViewRegistry<WorkspaceState["main"]>;
  let workspace = $state.raw<WorkspaceView | undefined>(undefined);
  let workspaceState = $state.raw<WorkspaceState | undefined>(undefined);
  let error = $state<string | undefined>(undefined);
  let unsubscribe = () => {};

  onMount(() => {
    let active = true;
    void connectWorkspace().then(client => {
      if (!active) { client.dispose(); return; }
      workspace = client;
      unsubscribe = client.subscribe(next => { workspaceState = next; });
    }).catch(cause => { error = String(cause); });
    return () => { active = false; unsubscribe(); workspace?.dispose(); };
  });

  async function run(command: () => Promise<unknown>) {
    try { await command(); error = undefined; }
    catch (cause) { error = String(cause); }
  }
</script>

<main>
  <header><h1>Runic Views</h1><p>Window/View starter · Svelte</p></header>
  <nav aria-label="Main navigation">
    <button onclick={() => workspace && run(() => workspace!.showWelcome())}>Welcome</button>
    <button onclick={() => workspace && run(() => workspace!.showCounter())}>Counter</button>
  </nav>
  <ViewOutlet content={workspaceState?.main} registry={pages} />
  <p role="status">{error ?? "Connected to the .NET Window."}</p>
</main>
