// examples/notes-view-first/Angular/src/app/confirm-navigation.ts
import { Component, DestroyRef, ElementRef, ViewChild, afterRenderEffect, inject, input } from "@angular/core";
import type { ConfirmNavigationPageReference } from "../../../Frontend/src/generated/confirmNavigation.js";
import { injectCommand } from "../../../../../packages/web/angular/src/inject-command";
import { injectPage, WindowOperations } from "./window-operations";

@Component({
  selector: "notes-confirm-navigation",
  template: `
    <div id="modal" class="modal" (keydown)="keydown($event)">
      <div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1">
        <h2 id="dialog-title">Unsaved changes</h2>
        <p data-message>{{ dialog.state()?.message ?? "Connecting…" }}</p>
        <div class="dialog-actions">
          <button #cancelButton data-cancel [disabled]="!dialog.state()?.canCancel" (click)="answer.run('cancel')">Keep editing</button>
          <button #confirmButton data-confirm [disabled]="!dialog.state()?.canConfirm" (click)="answer.run('confirm')">Discard changes</button>
        </div>
        @if (answer.error() ?? dialog.error(); as issue) { <p role="alert">{{ issue }}</p> }
        @if (dialog.error()) { <button (click)="dialog.retry()">Retry dialog</button> }
      </div>
    </div>
  `,
})
export class ConfirmNavigationComponent {
  readonly page = input.required<ConfirmNavigationPageReference>();
  readonly dialog = injectPage(this.page);
  private readonly operations = inject(WindowOperations);
  readonly answer = injectCommand((name: "cancel" | "confirm") =>
    this.operations.run(this.dialog.client(), view => view[name]()));
  private readonly destroyRef = inject(DestroyRef);
  private readonly previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
  private focused = false;
  private cancelElement: HTMLButtonElement | undefined;
  private confirmElement: HTMLButtonElement | undefined;

  @ViewChild("cancelButton") set cancelButton(ref: ElementRef<HTMLButtonElement> | undefined) {
    this.cancelElement = ref?.nativeElement;
  }
  @ViewChild("confirmButton") set confirmButton(ref: ElementRef<HTMLButtonElement> | undefined) {
    this.confirmElement = ref?.nativeElement;
  }

  constructor() {
    this.destroyRef.onDestroy(() => this.previousFocus?.focus());
    afterRenderEffect({ write: () => {
      if (this.dialog.state()?.canCancel && this.cancelElement && !this.focused) {
        this.cancelElement.focus();
        this.focused = true;
      }
    } });
  }

  keydown(event: KeyboardEvent): void {
    if (event.key === "Escape") {
      event.preventDefault();
      void this.answer.run("cancel");
    } else if (event.key === "Tab" && this.cancelElement && this.confirmElement) {
      if (event.shiftKey && document.activeElement === this.cancelElement) {
        event.preventDefault(); this.confirmElement.focus();
      } else if (!event.shiftKey && document.activeElement === this.confirmElement) {
        event.preventDefault(); this.cancelElement.focus();
      }
    }
  }
}

// examples/notes-view-first/Svelte/src/ConfirmNavigation.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { ConfirmNavigationPageReference } from "../../Frontend/src/generated/confirmNavigation.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";
  import { useCommand } from "../../../../packages/web/svelte/src/views/use-command.svelte.js";

  let { page }: { page: ConfirmNavigationPageReference } = $props();
  const dialog = useView(() => page);
  const answer = useCommand((name: "cancel" | "confirm") => dialog.client?.[name]());
  let cancelButton: HTMLButtonElement;
  let confirmButton: HTMLButtonElement;
  let focused = false;

  function keydown(event: KeyboardEvent) {
    if (event.key === "Escape") {
      event.preventDefault();
      void answer.run("cancel");
    }
    if (event.key === "Tab") {
      if (event.shiftKey && document.activeElement === cancelButton) {
        event.preventDefault(); confirmButton.focus();
      } else if (!event.shiftKey && document.activeElement === confirmButton) {
        event.preventDefault(); cancelButton.focus();
      }
    }
  }
  onMount(() => {
    const previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    return () => previousFocus?.focus();
  });
  $effect(() => {
    if (dialog.state?.canCancel && cancelButton && !focused) {
      cancelButton.focus();
      focused = true;
    }
  });
</script>

<div id="modal" class="modal" role="presentation" onkeydown={keydown}>
  <div class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1">
    <h2 id="dialog-title">Unsaved changes</h2>
    <p data-message>{dialog.state?.message ?? "Connecting…"}</p>
    <div class="dialog-actions">
      <button data-cancel bind:this={cancelButton} disabled={!dialog.state?.canCancel}
        onclick={() => answer.run("cancel")}>Keep editing</button>
      <button data-confirm bind:this={confirmButton} disabled={!dialog.state?.canConfirm}
        onclick={() => answer.run("confirm")}>Discard changes</button>
    </div>
    {#if answer.error ?? dialog.error}<p role="alert">{String(answer.error ?? dialog.error)}</p>{/if}
  </div>
</div>
