// examples/notes-view-first/Angular/src/app/sidebar.ts
import { Component, inject, input } from "@angular/core";
import type { SidebarPageReference } from "../../../Frontend/src/generated/sidebar.js";
import { injectCommand } from "../../../../../packages/web/angular/src/inject-command";
import { injectPage, WindowOperations } from "./window-operations";

@Component({
  selector: "notes-sidebar",
  template: `
    <h2>Workspace</h2>
    @if (sidebar.state(); as state) {
      <nav aria-label="Workspace navigation">
        <button data-go="home" [attr.aria-current]="state.selected === 'Home' ? 'page' : null"
          [disabled]="!state.canOpenHome" (click)="open.run('openHome')">Home</button>
        <button data-go="notes" [attr.aria-current]="state.selected === 'Notes' ? 'page' : null"
          [disabled]="!state.canOpenNotes" (click)="open.run('openNotes')">Notes</button>
      </nav>
    } @else { <p>Connecting…</p> }
    @if (open.error() ?? sidebar.error(); as issue) { <p role="alert">{{ issue }}</p> }
    @if (sidebar.error()) { <button (click)="sidebar.retry()">Retry sidebar</button> }
  `,
})
export class SidebarComponent {
  readonly page = input.required<SidebarPageReference>();
  readonly sidebar = injectPage(this.page);
  private readonly operations = inject(WindowOperations);
  readonly open = injectCommand((name: "openHome" | "openNotes") =>
    this.operations.run(this.sidebar.client(), view => view[name]()));
}

// examples/notes-view-first/Svelte/src/Sidebar.svelte
<script lang="ts">
  import type { SidebarPageReference } from "../../Frontend/src/generated/sidebar.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";
  import { useCommand } from "../../../../packages/web/svelte/src/views/use-command.svelte.js";

  let { page }: { page: SidebarPageReference } = $props();
  const sidebar = useView(() => page);
  const open = useCommand((name: "openHome" | "openNotes") => sidebar.client?.[name]());
</script>

<h2>Workspace</h2>
{#if sidebar.state && sidebar.client}
  <nav aria-label="Workspace navigation">
    <button data-go="home" aria-current={sidebar.state.selected === "Home" ? "page" : "false"}
      disabled={!sidebar.state.canOpenHome} onclick={() => open.run("openHome")}>Home</button>
    <button data-go="notes" aria-current={sidebar.state.selected === "Notes" ? "page" : "false"}
      disabled={!sidebar.state.canOpenNotes} onclick={() => open.run("openNotes")}>Notes</button>
  </nav>
{:else}
  <p>Connecting…</p>
{/if}
{#if open.error ?? sidebar.error}<p role="alert">{String(open.error ?? sidebar.error)}</p>{/if}
