// tools/Runic.Application.Templates/content/runic-app/frontends/vue/src/pages/CounterPage.vue
<script setup lang="ts">
import { useCommand, useView } from "@runic-artifex/vue";
import type { CounterPageReference } from "../generated/counter.js";

const props = defineProps<{ page: CounterPageReference }>();
const { state, client, error: connection } = useView(() => props.page);
const increment = useCommand(() => client.value?.increment());
</script>

<template>
  <section>
    <h2>Counter View</h2>
    <p class="count">{{ state?.count ?? "…" }}</p>
    <button :disabled="!client || increment.pending" @click="increment.run()">Increment</button>
    <p v-if="(increment.error ?? connection) !== undefined" role="alert">{{ String(increment.error ?? connection) }}</p>
  </section>
</template>

// tools/Runic.Application.Templates/content/runic-app/frontends/svelte/src/pages/CounterPage.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { useCommand, useView } from "@runic-artifex/svelte/views";
  import type { CounterPageReference } from "../generated/counter.js";

  let { page }: { page: CounterPageReference } = $props();
  const counter = useView(() => page);
  const increment = useCommand(() => counter.client?.increment());
  const error = $derived(increment.error ?? counter.error);
</script>

<section>
  <h2>Counter View</h2>
  <p class="count">{counter.state?.count ?? "…"}</p>
  <button disabled={!counter.client || increment.pending} onclick={() => increment.run()}>Increment</button>
  {#if error !== undefined}<p role="alert">{String(error)}</p>{/if}
</section>
