// tools/Runic.Application.Templates/content/vue/Frontend/src/pages/CounterPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import type { CounterPageReference, CounterState, CounterView } from "../generated/counter.js";

const props = defineProps<{ page: CounterPageReference }>();
const view = ref<CounterView>();
const state = ref<CounterState>();
const error = ref<string>();
let unsubscribe = () => {};
let active = true;

onMounted(() => {
  void props.page.connect().then(client => {
    if (!active) { client.dispose(); return; }
    view.value = client;
    unsubscribe = client.subscribe(next => { state.value = next; });
  }).catch(cause => { error.value = String(cause); });
});
onUnmounted(() => { active = false; unsubscribe(); view.value?.dispose(); });

async function increment() {
  try { await view.value?.increment(); error.value = undefined; }
  catch (cause) { error.value = String(cause); }
}
</script>

<template>
  <section>
    <h2>Counter View</h2>
    <p class="count">{{ state?.count ?? "…" }}</p>
    <button :disabled="!view" @click="increment">Increment</button>
    <p v-if="error" role="alert">{{ error }}</p>
  </section>
</template>

// tools/Runic.Application.Templates/content/react/Frontend/src/pages/CounterPage.tsx
import { useEffect, useState } from "react";
import type { CounterPageReference, CounterState, CounterView } from "../generated/counter.js";

export function CounterPage({ page }: { page: CounterPageReference }) {
  const [view, setView] = useState<CounterView>();
  const [state, setState] = useState<CounterState>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    let active = true;
    let unsubscribe = () => {};
    let client: CounterView | undefined;
    void page.connect().then(connected => {
      if (!active) { connected.dispose(); return; }
      client = connected;
      setView(connected);
      unsubscribe = connected.subscribe(next => setState(next));
    }).catch(cause => setError(String(cause)));
    return () => { active = false; unsubscribe(); client?.dispose(); };
  }, [page]);

  return <section>
    <h2>Counter View</h2>
    <p className="count">{state?.count ?? "…"}</p>
    <button disabled={!view} onClick={() => view && void view.increment().catch(cause => setError(String(cause)))}>Increment</button>
    {error && <p role="alert">{error}</p>}
  </section>;
}
