// tools/Runic.Application.Templates/content/svelte/Frontend/src/pages/WelcomePage.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { useView } from "@runic-artifex/svelte/views";
  import type { WelcomePageReference } from "../generated/welcome.js";

  let { page }: { page: WelcomePageReference } = $props();
  const welcome = useView(() => page);
</script>

<section>
  <h2>{welcome.state?.greeting ?? "Connecting…"}</h2>
  {#if welcome.error}<p role="alert">{String(welcome.error)}</p>{/if}
</section>

// tools/Runic.Application.Templates/content/react/Frontend/src/pages/WelcomePage.tsx
import { useView } from "@runic-artifex/react";
import type { WelcomePageReference } from "../generated/welcome.js";

export function WelcomePage({ page }: { page: WelcomePageReference }) {
  const { state, error } = useView(page);
  return <section><h2>{state?.greeting ?? "Connecting…"}</h2>{error !== undefined && <p role="alert">{String(error)}</p>}</section>;
}
