// tools/Runic.Application.Templates/content/vue/Frontend/src/pages/WelcomePage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import type { WelcomePageReference, WelcomeState, WelcomeView } from "../generated/welcome.js";

const props = defineProps<{ page: WelcomePageReference }>();
const state = ref<WelcomeState>();
const error = ref<string>();
let client: WelcomeView | undefined;
let unsubscribe = () => {};
let active = true;

onMounted(() => {
  void props.page.connect().then(connected => {
    if (!active) { connected.dispose(); return; }
    client = connected;
    unsubscribe = connected.subscribe(next => { state.value = next; });
  }).catch(cause => { error.value = String(cause); });
});
onUnmounted(() => { active = false; unsubscribe(); client?.dispose(); });
</script>

<template>
  <section><h2>{{ state?.greeting ?? "Connecting…" }}</h2><p v-if="error" role="alert">{{ error }}</p></section>
</template>

// tools/Runic.Application.Templates/content/react/Frontend/src/pages/WelcomePage.tsx
import { useEffect, useState } from "react";
import type { WelcomePageReference, WelcomeState, WelcomeView } from "../generated/welcome.js";

export function WelcomePage({ page }: { page: WelcomePageReference }) {
  const [state, setState] = useState<WelcomeState>();
  const [error, setError] = useState<string>();
  useEffect(() => {
    let active = true;
    let unsubscribe = () => {};
    let client: WelcomeView | undefined;
    void page.connect().then(connected => {
      if (!active) { connected.dispose(); return; }
      client = connected;
      unsubscribe = connected.subscribe(next => setState(next));
    }).catch(cause => setError(String(cause)));
    return () => { active = false; unsubscribe(); client?.dispose(); };
  }, [page]);
  return <section><h2>{state?.greeting ?? "Connecting…"}</h2>{error && <p role="alert">{error}</p>}</section>;
}
