// tools/Runic.Application.Templates/content/svelte/Frontend/src/App.svelte
<svelte:options runes={true} />

<script lang="ts">
  import { onMount } from "svelte";
  import { ViewOutlet, type ViewRegistry } from "@runic-artifex/svelte/views";
  import { connectWorkspace, type WorkspaceState, type WorkspaceView } from "./generated/workspace.js";
  import CounterPage from "./pages/CounterPage.svelte";
  import WelcomePage from "./pages/WelcomePage.svelte";

  const pages = { counter: CounterPage, welcome: WelcomePage } satisfies ViewRegistry<WorkspaceState["main"]>;
  let workspace = $state.raw<WorkspaceView | undefined>(undefined);
  let workspaceState = $state.raw<WorkspaceState | undefined>(undefined);
  let error = $state<string | undefined>(undefined);
  let unsubscribe = () => {};

  onMount(() => {
    let active = true;
    void connectWorkspace().then(client => {
      if (!active) { client.dispose(); return; }
      workspace = client;
      unsubscribe = client.subscribe(next => { workspaceState = next; });
    }).catch(cause => { error = String(cause); });
    return () => { active = false; unsubscribe(); workspace?.dispose(); };
  });

  async function run(command: () => Promise<unknown>) {
    try { await command(); error = undefined; }
    catch (cause) { error = String(cause); }
  }
</script>

<main>
  <header><h1>Runic Views</h1><p>Window/View starter · Svelte</p></header>
  <nav aria-label="Main navigation">
    <button onclick={() => workspace && run(() => workspace!.showWelcome())}>Welcome</button>
    <button onclick={() => workspace && run(() => workspace!.showCounter())}>Counter</button>
  </nav>
  <ViewOutlet content={workspaceState?.main} registry={pages} />
  <p role="status">{error ?? "Connected to the .NET Window."}</p>
</main>

// tools/Runic.Application.Templates/content/vue/Frontend/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { connectWorkspace, type WorkspaceState, type WorkspaceView } from "./generated/workspace.js";
import CounterPage from "./pages/CounterPage.vue";
import WelcomePage from "./pages/WelcomePage.vue";

const workspace = ref<WorkspaceView>();
const state = ref<WorkspaceState>();
const error = ref<string>();
let unsubscribe = () => {};
let active = true;

onMounted(() => {
  void connectWorkspace().then(client => {
    if (!active) { client.dispose(); return; }
    workspace.value = client;
    unsubscribe = client.subscribe(next => { state.value = next; });
  }).catch(cause => { error.value = String(cause); });
});

onUnmounted(() => {
  active = false;
  unsubscribe();
  workspace.value?.dispose();
});

async function run(command: () => Promise<unknown>) {
  try { await command(); error.value = undefined; }
  catch (cause) { error.value = String(cause); }
}

function showWelcome() {
  const client = workspace.value;
  if (client) void run(() => client.showWelcome());
}

function showCounter() {
  const client = workspace.value;
  if (client) void run(() => client.showCounter());
}
</script>

<template>
  <main>
    <header><h1>Runic Views</h1><p>Window/View starter · Vue</p></header>
    <nav aria-label="Main navigation">
      <button @click="showWelcome">Welcome</button>
      <button @click="showCounter">Counter</button>
    </nav>
    <CounterPage v-if="state?.main.kind === 'counter'" :key="state.main.kind" :page="state.main" />
    <WelcomePage v-else-if="state?.main.kind === 'welcome'" :key="state.main.kind" :page="state.main" />
    <p v-else>Connecting to the Window…</p>
    <p role="status">{{ error ?? "Connected to the .NET Window." }}</p>
  </main>
</template>
