// examples/notes-reactive-views/Angular/src/app/home.ts
import { Component, input } from "@angular/core";
import type { HomePageReference } from "../../../Frontend/src/generated/home.js";
import { injectView } from "../../../../../packages/web/angular/src/inject-view";

@Component({
  selector: "notes-home",
  template: `
    @if (home.state(); as state) { <h1>{{ state.greeting }}</h1><p>Open the document to see two Views of one Editor ViewModel.</p> }
    @else { <p>Connecting…</p> }
    @if (home.error(); as issue) { <p role="alert">{{ issue }}</p> }
  `,
})
export class HomeComponent {
  readonly page = input.required<HomePageReference>();
  readonly home = injectView(this.page);
}

// examples/notes-reactive-views/Svelte/src/Home.svelte
<script lang="ts">
  import type { HomePageReference } from "../../Frontend/src/generated/home.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";
  let { page }: { page: HomePageReference } = $props();
  const home = useView(() => page);
</script>

{#if home.state}
  <h1>{home.state.greeting}</h1>
  <p>Open the document to see two Views of one Editor ViewModel.</p>
{:else}
  <p>Connecting…</p>
{/if}
{#if home.error}<p role="alert">{String(home.error)}</p>{/if}
