// examples/notes-reactive-views/Angular/src/app/pinned-task.ts
import { Component, input } from "@angular/core";
import type { PinnedTaskPageReference } from "../../../Frontend/src/generated/pinnedTask.js";
import { injectView } from "../../../../../packages/web/angular/src/inject-view";

@Component({
  selector: "notes-pinned-task",
  template: `@if (task.state(); as state) { <span>Task: {{ state.priority }}</span> } @else { <span>Connecting…</span> }`,
})
export class PinnedTaskComponent {
  readonly page = input.required<PinnedTaskPageReference>();
  readonly task = injectView(this.page);
}

// examples/notes-reactive-views/Svelte/src/PinnedTask.svelte
<script lang="ts">
  import type { PinnedTaskPageReference } from "../../Frontend/src/generated/pinnedTask.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";

  let { page }: { page: PinnedTaskPageReference } = $props();
  const task = useView(() => page);
</script>

{#if task.state}<span>Task: {task.state.priority}</span>{:else}<span>Connecting…</span>{/if}
{#if task.error}<span role="alert">{String(task.error)}</span>{/if}
