// examples/notes-reactive-views/Angular/src/app/pinned-note.ts
import { Component, input } from "@angular/core";
import type { PinnedNotePageReference } from "../../../Frontend/src/generated/pinnedNote.js";
import { injectView } from "../../../../../packages/web/angular/src/inject-view";

@Component({
  selector: "notes-pinned-note",
  template: `@if (note.state(); as state) { <span>{{ state.label }}</span> } @else { <span>Connecting…</span> }`,
})
export class PinnedNoteComponent {
  readonly page = input.required<PinnedNotePageReference>();
  readonly note = injectView(this.page);
}

// examples/notes-reactive-views/Svelte/src/PinnedNote.svelte
<script lang="ts">
  import type { PinnedNotePageReference } from "../../Frontend/src/generated/pinnedNote.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";

  let { page }: { page: PinnedNotePageReference } = $props();
  const note = useView(() => page);
</script>

{#if note.state}<span>{note.state.label}</span>{:else}<span>Connecting…</span>{/if}
{#if note.error}<span role="alert">{String(note.error)}</span>{/if}
