// examples/notes-reactive-views/Angular/src/app/shell.ts
import { Component, input } from "@angular/core";
import type { ShellClient, ShellState } from "../../../Frontend/src/generated/shell.js";
import { injectCommand } from "../../../../../packages/web/angular/src/inject-command";
import { injectView } from "../../../../../packages/web/angular/src/inject-view";
import { HomeComponent } from "./home";
import { DocumentComponent } from "./document";
import { PinnedNoteComponent } from "./pinned-note";
import { PinnedTaskComponent } from "./pinned-task";
import { RunicViewOutlet, type ViewRegistry } from "../../../../../packages/web/angular/src/view-outlet";

const mainViews = { home: HomeComponent, document: DocumentComponent } satisfies ViewRegistry<ShellState["main"]>;
const pinnedViews = { pinnedNote: PinnedNoteComponent, pinnedTask: PinnedTaskComponent } satisfies ViewRegistry<ShellState["pinned"][number]>;

@Component({
  selector: "notes-shell",
  imports: [RunicViewOutlet],
  template: `
    <header><strong>Reactive Notes</strong><span>Angular · two View contracts</span></header>
    @if (state(); as current) {
      <div class="layout">
        <nav aria-label="Main navigation">
          <button data-go="home" [attr.aria-current]="current.main.kind === 'home' ? 'page' : null" (click)="command.run('openHome')">Home</button>
          <button data-go="document" [attr.aria-current]="current.main.kind === 'document' ? 'page' : null" (click)="command.run('openDocument')">Document</button>
        </nav>
        <main id="main"><runic-view-outlet [content]="current.main" [registry]="mainViews" /></main>
      </div>
    }
    @if (state(); as current) {
      <section id="pinned" aria-label="Pinned Views">
        <button data-pinned-action="swap" (click)="command.run('swapPinned')">Reorder pinned</button>
        <button data-pinned-action="remove" (click)="command.run('removePinned')">Remove pinned note</button>
        <button data-pinned-action="restore" (click)="command.run('restorePinned')">Restore pinned note</button>
        @for (item of current.pinned; track item) {
          <span [attr.data-pin]="item.kind"><runic-view-outlet [content]="item" [registry]="pinnedViews" /></span>
        }
      </section>
    }
    <p id="status" class="status" role="status">{{ command.error() ?? "Connected." }}</p>
  `,
})
export class ShellComponent {
  readonly shell = input.required<ShellClient>();
  readonly state = injectView(this.shell).state;
  readonly mainViews = mainViews;
  readonly pinnedViews = pinnedViews;
  readonly command = injectCommand((name: "openHome" | "openDocument" | "swapPinned" | "removePinned" | "restorePinned") =>
    this.shell()[name]());
}

// examples/notes-reactive-views/Svelte/src/Shell.svelte
<script lang="ts">
  import type { ShellClient, ShellState } from "../../Frontend/src/generated/shell.js";
  import { useView } from "../../../../packages/web/svelte/src/views/use-view.svelte.js";
  import { useCommand } from "../../../../packages/web/svelte/src/views/use-command.svelte.js";
  import Home from "./Home.svelte";
  import Document from "./Document.svelte";
  import PinnedNote from "./PinnedNote.svelte";
  import PinnedTask from "./PinnedTask.svelte";
  import ViewOutlet from "../../../../packages/web/svelte/src/views/ViewOutlet.svelte";
  import type { ViewRegistry } from "../../../../packages/web/svelte/src/views/view-registry.js";

  const mainViews = { home: Home, document: Document } satisfies ViewRegistry<ShellState["main"]>;
  const pinnedViews = { pinnedNote: PinnedNote, pinnedTask: PinnedTask } satisfies ViewRegistry<ShellState["pinned"][number]>;
  let { shell }: { shell: ShellClient } = $props();
  const source = useView(() => shell);
  let shellState = $derived(source.state!);
  const command = useCommand((name: "openHome" | "openDocument" | "swapPinned" | "removePinned" | "restorePinned") => shell[name]());
</script>

<header><strong>Reactive Notes</strong><span>Svelte · two View contracts</span></header>
<div class="layout">
  <nav aria-label="Main navigation">
    <button data-go="home" aria-current={shellState.main.kind === "home" ? "page" : "false"} onclick={() => command.run("openHome")}>Home</button>
    <button data-go="document" aria-current={shellState.main.kind === "document" ? "page" : "false"} onclick={() => command.run("openDocument")}>Document</button>
  </nav>
  <main id="main"><ViewOutlet content={shellState.main} registry={mainViews} /></main>
</div>
<section id="pinned" aria-label="Pinned Views">
  <button data-pinned-action="swap" onclick={() => command.run("swapPinned")}>Reorder pinned</button>
  <button data-pinned-action="remove" onclick={() => command.run("removePinned")}>Remove pinned note</button>
  <button data-pinned-action="restore" onclick={() => command.run("restorePinned")}>Restore pinned note</button>
  {#each shellState.pinned as pinned (pinned)}
    <span data-pin={pinned.kind}><ViewOutlet content={pinned} registry={pinnedViews} /></span>
  {/each}
</section>
<p id="status" role="status">{command.error === undefined ? "Connected." : String(command.error)}</p>
